init
BasedAlex/yadro-xkcd pull request #2
Opened 2024-03-25 21:34 UTC by BasedAlex

Initial solution for task 1

2024-03-27 15:33 UTC, kirreal requested changes

2024-03-27 15:33 UTC, kirreal commented on cmd/cli/dictionary.go
> +func dictionary() map[string]bool {
Не очень понятно зачем использовать функцию для обертки map?
Так же а нужно ли использовать значение bool в map?

2024-03-27 15:33 UTC, kirreal commented on cmd/cli/main.go
> +	res := make([]string, 0)
Тут можно использовать var res []string

2024-03-27 15:33 UTC, kirreal commented on cmd/cli/main.go
> +	for i := 0; i < len(words); i++ {
Тут можно использовать цикл без индекса. Сразу бежать по words через range - for _, w := range words {}

2024-03-27 15:33 UTC, kirreal commented on cmd/cli/main.go
> +	words := strings.Split(str, " ")
Делить нужно не только по пробелу, т.к. У нас могут быть и другие разделители - ".", ",", "!", "?" и т.д.
тут можно воспользоваться функцией FieldsFunc https://pkg.go.dev/strings#example-FieldsFunc

2024-03-27 15:33 UTC, kirreal commented on cmd/cli/dictionary.go
> +	filterMap["i'm"] = true
Апострофы так же могут встречаться в других кейсах, например "Alex's PR is not finished" или He's, He'll, can't и т.д.

2024-03-27 15:45 UTC, kirreal requested changes

2024-03-27 15:45 UTC, kirreal commented on cmd/cli/dictionary.go
> +	filterMap["i'm"] = true
Для английского языка вместо этой мапы можно воспользоваться готовой функцией из библиотеки snowball:
https://github.com/kljensen/snowball/blob/98e7b6e10cca8489481be24eaabcea4b5c2021f8/english/common.go#L206

2024-03-27 15:48 UTC, kirreal commented on cmd/cli/main.go
> +	words := strings.Split(str, " ")
Также после парса результатов необходимо проверить введенную строку и если она пустая выдать ошибку

2024-03-28 17:39 UTC, BasedAlex commented on cmd/cli/dictionary.go
> +func dictionary() map[string]bool {
fixed

2024-03-28 17:39 UTC, BasedAlex commented on cmd/cli/main.go
> +	res := make([]string, 0)
fixed

2024-03-28 17:40 UTC, BasedAlex commented on cmd/cli/main.go
> +	for i := 0; i < len(words); i++ {
fixed

2024-03-28 17:40 UTC, BasedAlex commented on cmd/cli/main.go
> +	words := strings.Split(str, " ")
fixed

2024-03-28 17:40 UTC, BasedAlex commented on cmd/cli/dictionary.go
> +	filterMap["i'm"] = true
fixed

2024-03-28 17:42 UTC, BasedAlex commented on cmd/cli/main.go
> +	words := strings.Split(str, " ")
fixed

2024-03-28 17:42 UTC, BasedAlex commented
@kirreal пофиксил

2024-03-29 11:32 UTC, kirreal reviewed
Уже почти все хорошо! Проверял на строке:
Isn't she lovely? By the way I believe she's got it and I'd like being aroud.

lovely by way i believ she got like aroud
Нужно убрать by, i, she

2024-03-29 11:32 UTC, kirreal commented on Makefile
> +
У меня из корня ошибка билда! Также, в задании было указано, что структура проекта должна быть плоской, без cmd/cli

2024-03-29 13:47 UTC, BasedAlex commented on Makefile
> +
Поправил архитектуру, должно работать

2024-03-29 13:48 UTC, BasedAlex commented
@kirreal очередной фикс :^)

2024-03-29 15:08 UTC, kirreal requested changes
Осталось make чуть-чуть исправить и все готово!

2024-03-29 15:08 UTC, kirreal commented on main.go
> +	pronouns := map[string]bool{
Тут уже, скорее warning - можно использовать map[string]interface{}, т.к. значение в map'е нам не так важно

2024-03-29 15:08 UTC, kirreal commented on Makefile
> +run:
А тут ошибка небольшая - второй критерий приемки:
при запуске make без аргументов должен появиться скомпилированный myapp.

2024-03-29 15:31 UTC, BasedAlex commented on main.go
> +	pronouns := map[string]bool{
Можно так и оставить ? Мне кажется таким образом короче проверка короче и понятнее

2024-03-29 15:32 UTC, BasedAlex commented on Makefile
> +run:
fixed

2024-03-29 15:38 UTC, kirreal commented on main.go
> +	pronouns := map[string]bool{
Ну да, можно и так, а проверка не измениться, мы же проверяем, есть ли значение в map'е, а если сделаем map[string]interface{}, то будем просто проверять, есть ли в map'е ключ.
Плюс, если map'a довольно большая. то сэкономим кучу памяти, т.к. interface{} ничего не занимает. Это так, совет на будущее

2024-03-29 15:38 UTC, kirreal approved these changes

2024-03-29 16:20 UTC, BasedAlex commented on main.go
> +	pronouns := map[string]bool{
Изменил, но не совсем понял как сократить 

```
if _, ok := map[value]; ok { 
    continue
}
```

2024-03-29 18:54 UTC, BasedAlex commented
@kirreal всё ок, могу вливать?

2024-03-30 16:49 UTC, merged