init
BasedAlex/yadro-xkcd pull request #4
Opened 2024-04-03 10:20 UTC by BasedAlex

initial pull request for Task-2

2024-04-04 15:59 UTC, kirreal requested changes

2024-04-04 15:59 UTC, kirreal commented on config.example.yaml
> +host: localhost
Я не очень понимаю зачем тут сервер, вроде, в задании такого требования нету

2024-04-04 15:59 UTC, kirreal commented on pkg/database/database.go
> +func WriteJSON(comics map[string]Page, cfg *config.Config) {
Из этой функции лучше возвращать ошибку и обрабатывать ее на вызывающей стороне.
Также с названием не очень понятно, лучше делать более абстрактные, ведь по факту тут сохранение списка комиксов - я бы порекомендовал SaveComics
Так же у нас тут не база данных по хранению json, а всего лишь кэш последнего состояния. Т.е. если мы запустим программу второй раз, то у нас все предыдущие данные удалятся.

2024-04-04 15:59 UTC, kirreal commented on cmd/xkcd/main.go
> +	srv := &http.Server{
В данной задаче создание сервера излишне

2024-04-04 15:59 UTC, kirreal commented on pkg/xkcd/client.go
> +func GetPages(cfg *config.Config) {
Функция не отражает название и тут смешиваются разные уровни логики. Если функция называется GetPages, то ожидается, что она сделает именно то, что написано вернет Pages. Т.е. лучше убрать из нее сохранение результата в базу и сделать GetPages(cfg *config.Config) (map[string]database.Page, error)

2024-04-04 15:59 UTC, kirreal commented on pkg/xkcd/client.go
> +type prepare struct {
Название структуры не очень понятное - тут скорее rawMessage или что-то вроде того.

2024-04-04 15:59 UTC, kirreal commented on config.example.yaml
> +start: 100
Не очень хорошая идея хранить start и limit в конфиг файле, limit еще можно оставить, но start по умолчанию должен быть 0 и будет не очень удобно менять. Т.е. если будет бинарник, то для получения от 0 до 1000, а потом от 1001 до 2000 нужно будет менять конфиг

2024-04-04 15:59 UTC, kirreal commented on pkg/config/config.go
> +	// configPathNew := "../../config.yaml"
Комментированный код надо удалить

2024-04-04 15:59 UTC, kirreal commented on pkg/database/database.go
> +	json.Unmarshal(dist, &comics)
Тут не обработана ошибка

2024-04-04 15:59 UTC, kirreal commented on pkg/database/database.go
> +func ReadJSON(cfg *config.Config) (map[string]Page, error) {
Тут я бы тоже переименовал во что-то более близкое к теме GetComics

2024-04-04 15:59 UTC, kirreal commented on pkg/database/database.go
> +	file, err := json.MarshalIndent(comics, "", " ")
Тут конечно вариант рабочий, но лишние символы в файле будут занимать лишнее место на диске. Лучше попробовать использовать json.Indent перед выдачей

2024-04-04 15:59 UTC, kirreal commented on pkg/xkcd/client.go
> +		Timeout: 10 * time.Second,
таймаут лучше вынести в константу

2024-04-04 15:59 UTC, kirreal commented on pkg/xkcd/client.go
> +	client := &http.Client{
А нужно ли нам каждый раз при получении страниц создавать клиент?

2024-04-04 15:59 UTC, kirreal commented on pkg/xkcd/client.go
> +		link := fmt.Sprintf("%s%d/info.0.json", cfg.Path, i)
Обычно такие переменные называются url :)

2024-04-04 15:59 UTC, kirreal commented on pkg/xkcd/client.go
> +		json.Unmarshal(content, &prep)
Не обрабатывается ошибка.
Так же если response будет не 200 то мы вернем пустую структуру

2024-04-04 15:59 UTC, kirreal commented on pkg/xkcd/client.go
> +			if counter > 10 {
А точно-ли это правильное место для проверки конца выборки?
Из документации client.Get

// An error is returned if caused by client policy (such as
// CheckRedirect), or failure to speak HTTP (such as a network
// connectivity problem). A non-2xx status code doesn't cause an
// error.

Т.е. эта ошибка будет не пустой в случае если у нас проблемы с протоколом, а не ошибка в response

2024-04-04 15:59 UTC, kirreal commented on pkg/xkcd/client.go
> +	database.WriteJSON(newPages, cfg)
Плохая практика смешивать логику получения данных и их сохранения. Этой операции тут не должно быть

2024-04-04 15:59 UTC, kirreal commented on pkg/xkcd/client.go
> +	if cfg.Print {
Плохая практика смешивать логику получения данных и их вывода. Этой операции тут не должно быть

2024-04-04 17:27 UTC, BasedAlex commented on pkg/database/database.go
> +	json.Unmarshal(dist, &comics)
done

2024-04-04 17:50 UTC, BasedAlex commented on pkg/xkcd/client.go
> +			if counter > 10 {
А если брать статус код из response и проверять на 4XX ошибки?

2024-04-04 18:20 UTC, BasedAlex commented on pkg/xkcd/client.go
> +	client := &http.Client{
Не совсем понял комментарий, всё пофиксил кроме этого момента

2024-04-05 09:10 UTC, kirreal commented on pkg/xkcd/client.go
> +			if counter > 10 {
Да, все верно, именно это и нужно сделать, только еще и 500 надо, можно вообще сделать проверку что, если response.code не 200, то считать ошибкой

2024-04-05 09:25 UTC, kirreal commented on pkg/database/database.go
> +func WriteJSON(comics map[string]Page, cfg *config.Config) {
Все же второй пункт про сохранение результатов предыдущего результата, про накопление и кэш последнего состояния в рамках данной задачи все же не нужен

2024-04-05 10:06 UTC, BasedAlex commented on pkg/database/database.go
> +func WriteJSON(comics map[string]Page, cfg *config.Config) {
Ок, удалил

2024-04-06 17:09 UTC, BasedAlex commented
@kirreal могу мерджить? вроде всё исправил

2024-04-08 12:15 UTC, vbelogrudov approved these changes
можно доулучшать в следующем задании

2024-04-08 12:34 UTC, merged