Task 4
BasedAlex/yadro-xkcd pull request #8
Opened 2024-04-17 16:53 UTC by BasedAlex

2024-04-19 15:24 UTC, kirreal requested changes
В индекс json попали странные символы "ã", предлоги "she" или "i" и цифровые значения, напрмер "000100111101110110011"
Также было бы здорово добавить хоть что-то о состоянии программы в лог.
Алгоритм пока не успел посмотреть, гляну отдельно

2024-04-19 15:24 UTC, kirreal commented on pkg/xkcd/client.go
> +func task(i int, results chan<- map[string]database.Page, client *http.Client, cfg *config.Config, ctx context.Context) {
Тут мелочь, но обычно Context передают первым параметром
Аргумент i int нигде в коде не используется, надо его удалить

2024-04-19 15:24 UTC, kirreal commented on pkg/indexer/indexer.go
> +	if _, err := os.Stat(pathToFile); !errors.Is(err, os.ErrNotExist) {
Тут прикольная конструкция, но сама ошибка так и не обрабатывается, т.е. если будет любая другая ошибка, то мы продолжим выолнение
Тут можно посмотреть что может пойти не так https://pkg.go.dev/os#pkg-variables

2024-04-19 15:24 UTC, kirreal commented on pkg/indexer/indexer.go
> +		intIndex, _ := strconv.Atoi(pagesIndex)
Ошибки лучше не игнорировать

2024-04-19 15:24 UTC, kirreal commented on pkg/indexer/indexer.go
> +	if _, err := os.Stat(pathToFile); !errors.Is(err, os.ErrNotExist) {
Тоже что и вверху

2024-04-19 15:24 UTC, kirreal commented on pkg/indexer/indexer.go
> +		intIndex, _ := strconv.Atoi(pagesIndex)
Ошибки лучше не игнорировать

2024-04-19 15:24 UTC, kirreal commented on pkg/database/database.go
> +	// f, err := os.Create("test.json")
Комментарии нужно удалить

2024-04-22 07:12 UTC, BasedAlex commented
@kirreal Обновил фетчинг даты, обновил алгоритм поиска индексов

2024-04-24 14:18 UTC, kirreal approved these changes

2024-04-24 15:06 UTC, merged